[versions]
agp = "8.2.2"
gson = "2.10.1"
kotlin = "1.9.22"

[libraries]
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

